### ISSUE TITLE
AC1214/10 not responding

### ISSUE THREAD

**Issue by mhabegger** [xMrVizzy/philips-airpurifier#6]
I have an Philips AC1214/10 which is connected to Wifi and which I can control using the Air-Matters application. however, it does not answer to http on it's IP and hassio reports `ConnectionRefusedError: [Errno 111] Connection refused` as well.

Do not all Air Purifiers support the same protocols ?

**Comment by xMrVizzy** [comment]
Idk, I'm using this library to control Philips Air Purifiers - https://github.com/rgerganov/py-air-control

**Comment by xMrVizzy** [comment]
The library may not support some models

**Comment by xMrVizzy** [comment]
It looks like it should be supported - https://github.com/rgerganov/py-air-control/issues/24

**Comment by SamMousa** [comment]
> Idk, I'm using this library to control Philips Air Purifiers - https://github.com/rgerganov/py-air-control

How are you using this library? You do not seem to be importing it, did you just copy its code?
-- if so, it could very well be that your copy is not up to date..

**Comment by xMrVizzy** [comment]
No the library is based on the same principle of connecting via a secret key, and the rest is just decryption and set values to home assistant sensor. The code responsible for the key is identical

**Comment by mhabegger** [comment]
It seems newer devices (from late 2019) use a different protocol: CoAP.
See: https://github.com/rgerganov/py-air-control/issues/21

**Comment by webosa** [comment]
Hi [https://github.com/rgerganov/py-air-control](https://github.com/rgerganov/py-air-control) works for me, with AC1214/10. I have a model from 2018 and using older version of the code.

**Comment by webosa** [comment]
I tried your code in Home Assistant, but I cannot get it to do anything. I admit that I am new to Home Assistant though, so could be I am doing something wrong there .. Installed it from HACS, and added those couple of lines to configuration.yaml .. restarted, but not sure what to do next, cannot see any new entities or devices.

**Comment by webosa** [comment]
.. and just after writing, it works :)

**Comment by 8811025080** [comment]
> .. and just after writing, it works :)

Hi, I have same issue like you. How did you manage to apper in Home Assistant? Could you please help me? I have done some process like you (installed via HACS)

**Comment by webosa** [comment]
> 
> 
> > .. and just after writing, it works :)
> 
> Hi, I have same issue like you. How did you manage to apper in Home Assistant? Could you please help me? I have done some process like you (installed via HACS)

I am not really sure what I did .. I think I did couple of HA and RPI4 restarts as I was playing at the same time with other stuff in deConz and and Node-red.

If i remember correctly I added the integration from HACS, added the config lines to my configuration.yaml and at first I did not see anything and when I checked again it was there.

Here is my config

## PHILIPS AIR PURIFIER ##
fan:
  - platform: philips-airpurifier
    host: <purifier ip address here>
    name: Philips Air Purifier

later I separated the PM2.5 to a separate sensor using Attributes from HACS and added this to my configuration.yaml

sensor:
  - platform: attributes
    friendly_name: "Purifier PM 2.5"
    attribute: pm25
    unit_of_measurement: "μg/m³"
    entities:
      - fan.philips_air_purifier

and in my ui-lovelace.yaml I have it customized a bit using using button-card, card-mod, mini-graph-card

          - type: horizontal-stack
            cards:
            
                # AIR PURIFIER #
              - type: custom:button-card
                entity: fan.philips_air_purifier
                show_name: true
                show_state: true
                show_icon: true
                tap_action:
                  action: more-info
                state:
                  - value: 'on'
                styles:
                  card:
                    - font-size: 1.1em
                style: |
                  ha-card {
                    height: 100%;
                  }
              - type: 'custom:mini-graph-card'
                entities:
                  - entity: sensor.philips_air_purifier_pm25
                    name: PM2.5
                font_size: 75
                font_size_header: 12
                align_header: center
                align_state: center
                hour24: true
                line_color: '#ff9900'
                line_width: 8
                show:
                  icon: false
                  extrema: true
                  name_adaptive_color: true

**Comment by 8811025080** [comment]
Thanks a lot for help, I did excatly the same but I just do not have it in HA or it is not working. Nothing appears. 

I have tried to put this code to my configuration.yaml
`sensor:
  - platform: attributes
    friendly_name: "Purifier PM 2.5"
    attribute: pm25
    unit_of_measurement: "μg/m³"
    entities:
     - fan.philips_air_purifie`

but then I get message:
`Platform error sensor.attributes - Integration 'attributes' not found.`


This is my configuration.yaml:

```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
panel_iframe:
  configurator:
    title: 'Configurator'
    url: 'http://192.168.100.XXX:3218'
    icon: mdi:wrench 
tado:
  username: 
  password: 
device_tracker:
  - platform: tado
    username: 
    password: 
    home_id: 
fan:
  - platform: philips-airpurifier
    host: 192.168.100.36
    protocol: 2
    name: Philips Air Purifier
sensor:
  - platform: attributes
    friendly_name: "Purifier PM 2.5"
    attribute: pm25
    unit_of_measurement: "μg/m³"
    entities:
     - fan.philips_air_purifie
binary_sensor:
  - platform: car_wash
    weather: weather.gismeteo_daily
```
